spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easyshop
    username: root
    password: Mah@moud1997
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

#  sql:
#    init:
#      mode: always

jwt:
  secret: 2f81f6a9a5c24e2f94b9d3f8d40358dfaf29dd274c7d489b82a1f46e44c29e377d97e80e4382d1c3e3b4d5f42ff3de39

  expiration: 86400000 # 1 day in milliseconds
