spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easyshop
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or "create" if you want to start fresh
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always

jwt:
  secret: mySuperSecretKey1234567890mySuperSecretKey1234567890
  expiration: 86400000 # 1 day in milliseconds
